### ISSUE TITLE
Use HashMap for retrieving and writing tag fields

### ISSUE THREAD

**Issue by amCap1712** [timusus/KTagLib#3]
Instead of directly creating an AudioFile in the JNI from TagLib's PropertyMap, it is better to convert it into a Java/Kotlin HashMap.
The HashMap can be mapped in the Kotlin code to produce an AudioFile. This way any new tag fields can be supported or removed by only changing the Kotlin code. This is beneficial as the JNI code does not provide any compile time safety. Errors in the JNI code will lead to runtime crashes whereas the compiler will catch a large number of errors at the compile time. @timusus Thoughts ?

**Comment by timusus** [comment]
Yes, agreed. I've actually merged in your changes :)

This helps align kTagLib as more of a wrapper around TagLib, which is what it should be.
